---
title: "exp1Analysis1209"
author: "zhuoran4"
date: "12/14/2020"
output: html_document
---

```{r}
data<-read.table('../data/exp1Res1125.csv',header=TRUE,sep=',')
low = data[data$idpAgreement==40,]
medium = data[data$idpAgreement==70,]
high = data[data$idpAgreement==100,]
  # data$idpAgreement = as.factor(data$idpAgreement)

aovTest = function(measure){
  data$idpAgreement = as.factor(data$idpAgreement)
  formula = as.formula(paste(measure,"idpAgreement",sep="~"))
  aovRes <- aov(formula, data = data)

  tukeyRes = TukeyHSD(aovRes, "idpAgreement" , ordered = TRUE)

  print(summary(aovRes))
  print(tukeyRes)
}

```
### Manipulation validity
```{r}
aovTest("actualAgreement")
```

### Main claim 
```{r}
aovTest("agreementFraction")
aovTest("switchFraction")
```
### Main claim non-parametric
```{r}
library(betareg)
data["switchFractionScaled"] = apply(data["switchFraction"],2,function(x) {(x+0.0001)/1.0002})
data["agreementFractionScaled"] = apply(data["agreementFraction"],2,function(x) {(x+0.0001)/1.0002})
part2 = betareg(switchFractionScaled~c(idpAgreement), data=data)
summary(part2)
part2 = betareg(agreementFractionScaled~c(idpAgreement), data=data)
summary(part2)
```

```{r}
kruskal.test(switchFraction ~ idpAgreement, data = data)
kruskal.test(agreementFraction ~ idpAgreement, data = data)

```
### Supporting variables
```{r}
measure = "competence"
measure_list = c("competence","reliability","understandability","faith")
for(i in c(1:length(measure_list))){
  measure = measure_list[i]
  low = data[data$idpAgreement==40,][measure]
  medium = data[data$idpAgreement==70,][measure]
  high = data[data$idpAgreement==100,][measure]
  
  
  res <- matrix(c(sum(low==-1),sum(low!=-1),sum(medium==-1),sum(medium!=-1),sum(high==-1),sum(high!=-1)),ncol=2,byrow=TRUE)
  
  
  res <- matrix(c(sum(low==1),sum(low!=1),sum(medium==1),sum(medium!=1),sum(high==1),sum(high!=1)),ncol=2,byrow=TRUE)
  
  colnames(res) <- as.factor(c("agree","other"))
  rownames(res) <- as.factor(c("low","medium","high"))
  res <- as.table(res)
  print("measurement:")
  print(measure)
  print("prop test:")
  print(prop.test(res)$p.value)
  print("pairwise prop test:")
  print(pairwise.prop.test(res))
  print("")
}

```