---
title: "exp2Analysis1209"
author: "zhuoran4"
date: "12/21/2020"
output: html_document
---

```{r}
data<-read.table('../data/exp2Res1125.csv',header=TRUE,sep=',')
agree50acc50 = data[data$idpAgreement==50 &data$acc==50 ,]
agree50acc80 = data[data$idpAgreement==50 &data$acc==80 ,]
agree80acc50 = data[data$idpAgreement==80 &data$acc==50 ,]
agree80acc80 = data[data$idpAgreement==80 &data$acc==80 ,]
data$idpAgreement = as.factor(data$idpAgreement)
data$acc = as.factor(data$acc)
data$treatment = as.factor(data$treatment)
```

```{r}
switchFractionRes <- aov(switchFraction ~ acc*idpAgreement, data = data)
summary(switchFractionRes)
TukeyHSD(switchFractionRes, ordered = TRUE)
```
```{r}
agreementFractionRes <- aov(agreementFraction ~ acc*idpAgreement, data = data)
summary(agreementFractionRes)
TukeyHSD(agreementFractionRes, ordered = TRUE)
```
```{r}
trustSurveyRes <- aov(trustSurvey ~ acc*idpAgreement, data = data)
summary(trustSurveyRes)
TukeyHSD(trustSurveyRes, ordered = TRUE)
```
```{r}
data["switchFractionScaled"] = apply(data["switchFraction"],2,function(x) {(x+0.0001)/1.0002})
data["agreementFractionScaled"] = apply(data["agreementFraction"],2,function(x) {(x+0.0001)/1.0002})
part2 = betareg(switchFractionScaled~idpAgreement*acc, data=data)
summary(part2)
part2 = betareg(agreementFractionScaled~idpAgreement*acc, data=data)
summary(part2)
```



```{r}
measure_vec = c("understandability","competence","faith","reliability")
measure = measure_vec[4]
prop_test = function (measure,attitude){
  agree50acc50 = data[data$idpAgreement==50 &data$acc==50 ,][measure]
  agree50acc80 = data[data$idpAgreement==50 &data$acc==80 ,][measure]
  agree80acc50 = data[data$idpAgreement==80 &data$acc==50 ,][measure]
  agree80acc80 = data[data$idpAgreement==80 &data$acc==80 ,][measure]
  tvec = c(agree50acc50,agree50acc80,agree80acc50,agree80acc80)
  
    
    
    print(paste("measurement :",measure,"(",(if(attitude==1) "agree" else "disagree"),")"))
  print(prop.test(c(sum(agree80acc80==attitude),sum(agree50acc80==attitude),sum(agree80acc50==attitude),sum(agree50acc50==attitude)), c(nrow(agree80acc80),nrow(agree50acc80),nrow(agree80acc50),nrow(agree50acc50)))$p.value)
  
}

for(elem in measure_vec){
  prop_test(elem,1)
  prop_test(elem,-1)


}


```
```{r}
propTestPairwise = function(measure,symbol){
  agree50acc50 = data[data$idpAgreement==50 &data$acc==50 ,][measure]
  agree50acc80 = data[data$idpAgreement==50 &data$acc==80 ,][measure]
  agree80acc50 = data[data$idpAgreement==80 &data$acc==50 ,][measure]
  agree80acc80 = data[data$idpAgreement==80 &data$acc==80 ,][measure]
  
  
  nobs = c(nrow(agree50acc50),nrow(agree50acc80),nrow(agree80acc50),nrow(agree80acc80))
  success = c(sum(agree50acc50==symbol),sum(agree50acc80==symbol),sum(agree80acc50==symbol),sum(agree80acc80==symbol))
  pvalue = (pairwise.prop.test(success,nobs)$p.value)

  dim(pvalue)=c(3,3)
  # return(typeof(res))
  colnames(pvalue) <- c("agree50acc50",'agree50acc80','agree80acc50')
  rownames(pvalue) <- c('agree50acc80','agree80acc50','agree80acc80')
  print(pvalue)
  print(prop.test(success,nobs))


}
```
# faith
```{r}
propTestPairwise("faith",1)
propTestPairwise("faith",-1)
```
# competence
```{r}
propTestPairwise("competence",1)
propTestPairwise("competence",-1)
```
# reliability
```{r}
propTestPairwise("reliability",1)
propTestPairwise("reliability",-1)
```
# understandability
```{r}
propTestPairwise("understandability",1)
propTestPairwise("understandability",-1)
```

